### ISSUE TITLE
Uncaught Error: Unexpected directive

### ISSUE THREAD

**Issue by VitaliyKovtun** [NagRock/ngx-auto-scroll#3]
Hey, guys. What am I doing wrong?
Uncaught Error: Unexpected directive 'Angular2AutoScroll' imported by the module 'AppModule'
I do
import { Angular2AutoScroll } from 'angular2-auto-scroll/lib/angular2-auto-scroll.directive';
to app.module.ts
and
Angular2AutoScroll
to
imports: [
    IonicModule.forRoot(MyApp),
    Angular2AutoScroll
]

**Comment by NagRock** [comment]
Can you provide angular version or even better a sample project?

18 sty 2017 4:43 PM "VitaliyKovtun" <notifications@github.com> napisał(a):

**Comment by netopolit** [comment]
@VitaliyKovtun Since Angular2AutoScroll is not a module but a directive you should add it to declarations list, not the imports list.

**Comment by NagRock** [comment]
As @netopolit said you should add it to declaration list in your module.

Closing
