### ISSUE TITLE
support for angular AOT

### ISSUE THREAD

**Issue by ahmed-musallam** [NagRock/ngx-auto-scroll#5]
Hi, there was a question on stackoverflow that I answered where this directive does not work with AOT. Please see my answer to the question if you'd like to make this directive compatible with AOT.

http://stackoverflow.com/questions/43166491/angular2-build-under-angular-cli-with-directive-and-ng-build-prod/43172360?noredirect=1#comment73418872_43172360

I'd also say, you should probably expose the source TS file alongside the generated JS file in the published package. In a new release of course.

**Comment by seiyria** [comment]
Please do this, I don't like pulling dependencies in manually!

**Comment by NagRock** [comment]
@seiyria maybe You want to contribute with this?

**Comment by seiyria** [comment]
@NagRock see #7

**Comment by beradrian** [comment]
Is there any plan to fix this issue?

**Comment by beradrian** [comment]
I guess this issue can be closed now, right?

**Comment by NagRock** [comment]
Done in 1.1.0 version.
