### ISSUE TITLE
can you provide a live demo?

### ISSUE THREAD

**Issue by jamessawyer** [NagRock/ngx-auto-scroll#9]
I have no idea of  how to use it, Follow by your readme.md, but it did not work

**Comment by beradrian** [comment]
That's because of issue #8 most probably, but I submitted a PR for this.

If not, what's the issue?

**Comment by NagRock** [comment]
Sample project: https://github.com/NagRock/ngx-auto-scroll-example
Demo: https://stackblitz.com/github/NagRock/ngx-auto-scroll-example
